 steps:
 # build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/${PROJECT_ID}-cloudrun:$COMMIT_SHA', 'backend']
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/${PROJECT_ID}-cloudrun:$COMMIT_SHA']
 # Deploy container image from Container Registry to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - 'run'
   - 'deploy'
   - '${PROJECT_ID}-cloudrun'
   - '--image'
   - 'gcr.io/$PROJECT_ID/${PROJECT_ID}-cloudrun:$COMMIT_SHA'
   - '--region'
   - 'asia-east1'
   - '--platform'
   - 'managed'
   - '--allow-unauthenticated'
 images:
 - 'gcr.io/$PROJECT_ID/${PROJECT_ID}-cloudrun:$COMMIT_SHA'