version: '3.1'

services:
  db:
    image: postgres
    volumes:
      - ./postgresql/data/:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    restart: always
