pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'pwd'
                sh 'ls'
                sh 'chmod 777 backend'
                sh 'cd backend'
                sh 'virtualenv env'
                sh 'source env/bin/activate'
                sh 'pip install -r requirements.txt'
                sh 'python manage.py collectstatic'
            }
        }
        stage('Test') {
            steps {
                /* sh 'cd backend' */
                /* sh 'python manage.py test' */
                sh 'pwd'
            }
        }
        stage('Deploy - Staging') {
            steps {
                sh 'echo "Staging"'
            }
        }
        stage('Deploy - Production') {
            steps {
                sh 'echo "Production"'
            }
        }
    }
    post {
        always {
            /* deleteDir() */ /* clean up our workspace */
        }
        success {
            echo 'This will run only if successful'
        }
        failure {
            echo 'This will run only if failed'
        }
        unstable {
            echo 'This will run only if the run was marked as unstable'
        }
        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }
    }
}
