# Continuous deployment from git using Cloud Build: https://cloud.google.com/run/docs/continuous-deployment-with-cloud-build
# Creating and managing build triggers: https://cloud.google.com/cloud-build/docs/running-builds/create-manage-triggers
# Google Cloud Build: https://dragonprogrammer.com/building-docker-image-google-cloud-build/ 

steps:
# Clone the repository.
- name 'gcr.io/cloud-builders/git'
  args:
  - clone
  - '--depth'
  - '1'
  - https://github.com/alanwuha/ntucourses.git

# Build and tag the image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ntucourses/version1', './backend']

# Publish the image to Container Registry.
- images: ['gcr.io/ntucourses/version1']