# Generated by Django 3.0.5 on 2020-04-12 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20200412_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='course_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.Course'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='course_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.Course'),
        ),
    ]
