# Generated by Django 3.0.5 on 2020-04-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20200412_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(choices=[('LT', 'Lecture Theatre'), ('LIB', 'Library'), ('EH', 'Examination Hall'), ('MR', 'Meeting Room'), ('RR', 'Reading Room'), ('SR', 'Seminar Room'), ('TR', 'Tutorial Room'), ('TR+', 'Tutorial Room +'), ('LAB', 'Laboratory')], max_length=3),
        ),
    ]
