# Generated by Django 3.0.5 on 2020-04-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_auto_20200412_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='unit',
            field=models.CharField(max_length=100),
        ),
    ]
