# Generated by Django 3.0.5 on 2020-04-13 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0009_auto_20200412_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='scraping.Course'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='scraping.Course'),
        ),
    ]
