# Generated by Django 3.0.5 on 2020-05-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0013_auto_20200513_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['course_code', '-year', '-semester', 'index', 'class_type', 'group', 'day', 'start_time', 'end_time']},
        ),
        migrations.RemoveConstraint(
            model_name='class',
            name='unique_class',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='course_code_id',
            new_name='course_code',
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('index', 'class_type', 'group', 'day', 'start_time', 'end_time', 'venue', 'remark', 'course_code', 'year', 'semester'), name='unique_class'),
        ),
    ]
