# Generated by Django 3.0.5 on 2020-05-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0014_auto_20200513_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='unrestricted_elective',
            field=models.BooleanField(default=False),
        ),
    ]
