# Generated by Django 3.0.5 on 2020-05-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0015_course_unrestricted_elective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='unrestricted_elective',
        ),
    ]
