# Generated by Django 3.0.5 on 2020-05-20 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0016_remove_course_unrestricted_elective'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='SYSTEM', max_length=20)),
                ('last_updated_datetime', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(default='SYSTEM', max_length=20)),
                ('programme_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['programme_code', 'description'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='SYSTEM', max_length=20)),
                ('last_updated_datetime', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(default='SYSTEM', max_length=20)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='scraping.Course')),
                ('programme_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Programme', to='scraping.Programme')),
            ],
            options={
                'ordering': ['programme_code', 'course_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='programmecourse',
            constraint=models.UniqueConstraint(fields=('programme_code', 'course_code'), name='unique_programme_course'),
        ),
    ]
