# Generated by Django 3.0.5 on 2020-05-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0017_auto_20200521_0006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgrammeCourse',
        ),
    ]
