# Generated by Django 3.0.5 on 2020-05-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0019_auto_20200521_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='programme_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
