# Generated by Django 3.0.5 on 2020-05-20 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0020_auto_20200521_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmecourse',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='scraping.Course'),
        ),
        migrations.AlterField(
            model_name='programmecourse',
            name='programme_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='scraping.Programme'),
        ),
    ]
