# Generated by Django 3.0.5 on 2020-05-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0022_auto_20200521_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='programme_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
