# Generated by Django 3.0.5 on 2020-05-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0023_auto_20200521_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='programme_type',
            field=models.CharField(blank=True, choices=[('SD', 'Single Degree'), ('DD', 'Double Degree'), ('MI', 'Minor'), ('GE', 'General Education'), ('SP', 'Scholars'), ('UE', 'Unrestricted Electives')], max_length=2),
        ),
    ]
