# Generated by Django 3.0.5 on 2020-05-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0024_programme_programme_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='programme_type',
            field=models.CharField(choices=[('SD', 'Single Degree'), ('DD', 'Double Degree'), ('MI', 'Minor'), ('GE', 'General Education'), ('SP', 'Scholars'), ('UE', 'Unrestricted Electives')], max_length=2),
        ),
    ]
