# Generated by Django 3.0.5 on 2020-04-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20200412_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='SYSTEM', max_length=20)),
                ('last_updated_datetime', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(default='SYSTEM', max_length=20)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('unit', models.CharField(max_length=20)),
                ('venue_type', models.CharField(choices=[('LT', 'Lecture Theatre'), ('LIB', 'Library'), ('EH', 'Examination Hall'), ('MR', 'Meeting Room'), ('RR', 'Reading Roomm'), ('SR', 'Seminar Room'), ('TR', 'Tutorial Room'), ('TR+', 'Tutorial Room +'), ('LAB', 'Laboratories')], max_length=3)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['course_code', '-year', '-semester', 'day', 'start_time', 'group']},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['course_code', '-year', '-semester', 'date', 'time']},
        ),
    ]
