# Generated by Django 3.0.4 on 2020-03-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_auto_20200331_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='mutually_exclusive_with',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='not_available_as_core_to_programme',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='not_available_as_pe_to_programme',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='not_available_as_ue_to_programme',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='not_available_to_all_programme_with',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='not_available_to_programme',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisite',
            field=models.TextField(blank=True),
        ),
    ]
