# Generated by Django 3.0.4 on 2020-04-07 08:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_auto_20200331_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.CharField(default='SYSTEM', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='last_updated_by',
            field=models.CharField(default='SYSTEM', max_length=20),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='SYSTEM', max_length=20)),
                ('last_updated_datetime', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(default='SYSTEM', max_length=20)),
                ('class_type', models.CharField(blank=True, choices=[('lec', 'Lecture'), ('tut', 'Tutorial'), ('lab', 'Laboratory'), ('sem', 'Seminar')], max_length=3)),
                ('group', models.CharField(blank=True, max_length=6)),
                ('day', models.CharField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=20)),
                ('remark', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(9999)])),
                ('semester', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('course_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraping.Course')),
            ],
            options={
                'ordering': ['course_code', '-year', '-semester'],
            },
        ),
    ]
